import type { MapDef } from '../mapData';

// Generated by the map builder, then hand-tuned. Runaway minecarts, TNT everywhere and a very cold lake.
export const mine: MapDef = {
  id: 'mine',
  name: 'ABANDONED MINE',
  theme: 'mine',
  blurb: 'Runaway minecarts, TNT everywhere and a very cold lake.',
  killMargin: 48,
  rows: [
    'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD', // 0
    'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD', // 1
    'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD', // 2
    'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD', // 3
    'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD', // 4
    'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD', // 5
    'DDDDDDDDDD:::::::::::::::::::::::::::::::::::::::::::::::::::::DDDDDDDDDDDDD', // 6
    'DDDDDDDDDD:::::::::::::::::::::::::::::::::::::::::::::::::::::DDDDDDDDDDDDD', // 7
    'DDDDDDDDDD::::::::::::::::::-------------------::::::::::::::::DDDDDDDDDDDDD', // 8
    'DDDDDDDDDD:::::::::::::::::::::::::::::::::::::::::::::::::::::DDDDDDDDDDDDD', // 9
    'DDDDDDDDDD:::::::::::::::::::::::::::::::::::::::::::::::::::::DDDDDDDDDDDDD', // 10
    'DDDDDDDDDD::::c:::S:::::::::::w:::::::::b:::S::::::::::::w:::::DDDDDDDDDDDDD', // 11
    'DDDDD::H::DDDDDDDDDD::H::DDDDDDDDDDDDDDDDDDDDDDDDD::H::DDDDDDDDD::H::DDDDDDD', // 12
    'DDDDD::H::DDDDDDDDDD::H::DDDDDDDDDDDDDDDDDDDDDDDDD::H::DDDDDDDDD::H::DDDDDDD', // 13
    'DDDDD::H::DDDDDDDDDD::H::DDDDDDDDDDDDDDDDDDDDDDDDD::H::DDDDDDDDD::H::DDDDDDD', // 14
    'DDDDD::H::DDDDDDDDDD::H::DDDDDDDDDDDDDDDDDDDDDDDDD::H::DDDDDDDDD::H::DDDDDDD', // 15
    'DDDDD::H::DDDDDDDDDD::H::DDDDDDDDDDDDDDD::::::::::::H:::::::::::::H:::::::DD', // 16
    'DD:::::H::::::::::::::H:::::::::::::::::::::::::::::H:::::::::::::H:::::::DD', // 17
    'DD:::::H::::::::::::::H::::::::::::::::::::::----------------:::::H:::::::DD', // 18
    'DD:::::H::::::-------------:::::::::::::::::::::::::H:::::::::::::H:::::::DD', // 19
    'DD:::::H::::::::::::::H:::::::::::::::::::::::::::::H:::::::::::::H:::::::DD', // 20
    'DD:::::H::::::::::::::H:::::::::::::w::::::::w::::::H:::::::S:::::H:::t:::DD', // 21
    'DD:::::H:::::::S::::::H:c:w:::-----H-----DDDDDDDDDDDDDDDDDDDDDDDDDHDDDDDDDDD', // 22
    'DDDDDDDHDDDDDDDDDDDDDDDDDDDDDD:::::H:::::DDDDDDDDDDDDDDDDDDDDDDDDDHDDDDDDDDD', // 23
    'DDDDDDDHDDDDDDDDDDDDDDDDDDDDDD:::::H:::::DDDDDDDDDDDDDDDDDDDDDDDDDHDDDDDDDDD', // 24
    'DDDDDDDHDDDDDDDDDDDDDDDDDDDDDD:::::H:::::DDDDDDDDDDDDDDDDDDDDDDDDDHDDDDDDDDD', // 25
    'DD:::::H:::::::::::::::::::::::::::H::::::::::::::::::::::::::::::H:::::::DD', // 26
    'DD:::::H::::W:::::::::::::::W::::::H:::::::::::W::::::::::W:::::::H:::::::DD', // 27
    'DD:::::H:::::::::::::::::::::::::::H::::::::::::::::::::::::::::::H:::::::DD', // 28
    'DD:::::H:::::::::::::::::::::::::::H::::::::::::::::::::::::::::::H:::::::DD', // 29
    'DD:::::H::::W:::::::::::::::W::::::H:::::::::::W::::::::::W:::::::H:::::::DD', // 30
    'DD::S::Hw:t:W::::S::t::::S::W:::::---::::::::::W::S::::t::W:::S:::Ht:::S::DD', // 31
    'DDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX~~~~~~~~~XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXDD', // 32
    'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD~~~~~~~~~DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD', // 33
    'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD', // 34
    'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD', // 35
  ],
  gimmicks: [
    {
      'type': 'mover',
      'kind': 'cart',
      'x': 2,
      'y': 31.25,
      'w': 2,
      'h': 12,
      'path': [
        [
          28,
          0
        ]
      ],
      'speed': 150,
      'pause': 2.5,
      'hits': {
        'damage': 30,
        'knock': 320
      }
    },
    {
      'type': 'mover',
      'kind': 'cart',
      'x': 71,
      'y': 31.25,
      'w': 2,
      'h': 12,
      'path': [
        [
          -28,
          0
        ]
      ],
      'speed': 150,
      'pause': 3.5,
      'hits': {
        'damage': 30,
        'knock': 320
      }
    }
  ],
};
