import type { MapDef } from '../mapData';

// Generated by the map builder, then hand-tuned. Leap between skyscrapers. Mind the gap. Choppers drop heavy hardware.
export const neonRooftops: MapDef = {
  id: 'rooftops',
  name: 'NEON ROOFTOPS',
  theme: 'rooftops',
  blurb: 'Leap between skyscrapers. Mind the gap. Choppers drop heavy hardware.',
  killMargin: 40,
  rows: [
    '..........................................................................', // 0
    '..........................................................................', // 1
    '..........................................................................', // 2
    '..........................................................................', // 3
    '..........................................................................', // 4
    '..........................................................................', // 5
    '..........................................................................', // 6
    '..........................................................................', // 7
    '..........................................................................', // 8
    '..........................................................................', // 9
    '....................................................w.....................', // 10
    '.......................w........................========H=................', // 11
    '....................=====H==...........w................H.................', // 12
    '.........................H............MMMM..............H.................', // 13
    '...........w.............H............MMMM..............H.................', // 14
    '........-----........MM..H............MMMM..............H...........w.....', // 15
    '.....................MM..H............MMMM.........MMM..H.......------H--.', // 16
    '..................cS.MM.wH...S.....-H------........MMM..H.............H...', // 17
    '.................#########GGG##.....H............S.MMMb.HS............H...', // 18
    '.................BBBBBBBBBBBBBB.....H..........############...........H...', // 19
    '....MMM..........BBBBBBBBBBBBBB.....H..........BBBBBBBBBBBB...........H...', // 20
    '..ScMMM..S..b....BBBBBBBBBBBBBB.....H..........BBBBBBBBBBBB---....MM..H...', // 21
    '##############---BBBBBBBBBBBBBB.....HXX........BBBBBBBBBBBB....cS.MM..H.S.', // 22
    'BBBBBBBBBBBBBB...BBBBBBBBBBBBBB....SHXX..wSg...BBBBBBBBBBBB...############', // 23
    'BBBBBBBBBBBBBB...BBBBBBBBBBBBBB...##########...BBBBBBBBBBBB...BBBBBBBBBBBB', // 24
    'BBBBBBBBBBBBBB...BBBBBBBBBBBBBB...BBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBBB', // 25
    'BBBBBBBBBBBBBB...BBBBBBBBBBBBBB...BBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBBB', // 26
    'BBBBBBBBBBBBBB...BBBBBBBBBBBBBB...BBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBBB', // 27
    'BBBBBBBBBBBBBB...BBBBBBBBBBBBBB...BBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBBB', // 28
    'BBBBBBBBBBBBBB...BBBBBBBBBBBBBB...BBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBBB', // 29
    'BBBBBBBBBBBBBB...BBBBBBBBBBBBBB...BBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBBB', // 30
    'BBBBBBBBBBBBBB...BBBBBBBBBBBBBB...BBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBBB', // 31
    'BBBBBBBBBBBBBB...BBBBBBBBBBBBBB...BBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBBB', // 32
    'BBBBBBBBBBBBBB...BBBBBBBBBBBBBB...BBBBBBBBBB...BBBBBBBBBBBB...BBBBBBBBBBBB', // 33
  ],
  gimmicks: [
    {
      'type': 'drops',
      'every': [
        14,
        22
      ],
      'xs': [
        8,
        24,
        39,
        52,
        68
      ],
      'pool': [
        'minigun',
        'bazooka',
        'sniper',
        'rifle',
        'flamer',
        'bullettime'
      ]
    }
  ],
};
