# Usage: python3 scripts/mapgen.py [ids...]  (regenerates the themed maps, or only the named ones,
#        e.g. `python3 scripts/mapgen.py leaf ship alien`; testArena.ts is hand-written)
# Map builder for SCRAPYARD RIOT. Emits src/sim/map/maps/<id>.ts (ASCII rows + gimmicks).
import json, sys
import os
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'sim', 'map', 'maps') + os.sep

class G:
    def __init__(s, w, h, fill='.'):
        s.w, s.h = w, h
        s.g = [[fill] * w for _ in range(h)]
    def p(s, x, y, c):
        if 0 <= x < s.w and 0 <= y < s.h: s.g[y][x] = c
    def get(s, x, y):
        return s.g[y][x] if 0 <= x < s.w and 0 <= y < s.h else '.'
    def rect(s, x0, y0, x1, y1, c):
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1): s.p(x, y, c)
    def hl(s, x0, x1, y, c): s.rect(x0, y, x1, y, c)
    def vl(s, x, y0, y1, c): s.rect(x, y0, x, y1, c)
    def back(s, x0, y0, x1, y1):
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1):
                if s.get(x, y) == '.': s.p(x, y, ':')
    def ladder(s, x, y0, y1):
        """ladder column from y0 (top cell, usually the platform row) down to y1 (cell above the floor)"""
        s.vl(x, y0, y1, 'H')
    def mark(s, x, floor_y, c):
        """put a marker standing on the floor row floor_y (nudged sideways if the cell is taken)"""
        for dx in [0, 1, -1, 2, -2, 3, -3, 4, -4]:
            xx = x + dx
            if s.get(xx, floor_y - 1) in '.:' and s.get(xx, floor_y - 2) in '.:' and s.get(xx, floor_y) not in '.:~':
                if dx: print('  nudged', c, x, '->', xx, 'row', floor_y)
                s.p(xx, floor_y - 1, c)
                return
        raise AssertionError(('no room for marker', c, x, floor_y))
    def rows(s):
        return [''.join(r) for r in s.g]

def emit(var, mid, name, theme, blurb, g, gimmicks=None, kill=48, power_bias=None):
    rows = g.rows()
    n = sum(r.count('S') for r in rows)
    assert n == 10, (mid, 'spawns', n)
    lines = [f"import type {{ MapDef }} from '../mapData';", '', f'// Generated by the map builder, then hand-tuned. {blurb}',
             f'export const {var}: MapDef = {{', f"  id: '{mid}',", f"  name: '{name}',", f"  theme: '{theme}',", f"  blurb: '{blurb}',", f'  killMargin: {kill},'] + ([f"  powerBias: '{power_bias}',"] if power_bias else []) + ['  rows: [']
    for i, r in enumerate(rows): lines.append(f"    '{r}', // {i}")
    lines.append('  ],')
    if gimmicks:
        lines.append('  gimmicks: ' + json.dumps(gimmicks, indent=2).replace('\n', '\n  ').replace('"', "'") + ',')
    lines.append('};')
    open(OUT + mid + '.ts', 'w').write('\n'.join(lines) + '\n')
    print(mid, g.w, 'x', g.h)

# ------------------------------------------------------------------ NEON ROOFTOPS
def rooftops():
    W, H = 74, 34
    g = G(W, H)
    # buildings: (x0, x1, roof row)
    bld = [(0, 13, 22), (17, 30, 18), (34, 43, 24), (47, 58, 19), (62, 73, 23)]
    for x0, x1, r in bld:
        g.rect(x0, r, x1, H - 1, 'B')
        g.hl(x0, x1, r, '#')
    # rooftop furniture
    g.rect(4, 20, 6, 21, 'M')            # AC unit
    g.rect(21, 15, 22, 17, 'M')          # stairwell box
    g.hl(20, 27, 12, '=')                # billboard catwalk
    g.vl(25, 12, 17, 'H')
    g.rect(37, 22, 38, 23, 'X')          # vent
    g.hl(35, 42, 17, '-')                # water tower deck (wood)
    g.vl(36, 17, 23, 'H')
    g.rect(38, 13, 41, 16, 'M')          # water tank
    g.rect(51, 16, 53, 18, 'M')          # AC
    g.hl(48, 57, 11, '=')                # neon sign scaffold
    g.vl(56, 11, 18, 'H')
    g.rect(66, 21, 67, 22, 'M')
    g.hl(64, 72, 16, '-')
    g.vl(70, 16, 22, 'H')
    g.hl(8, 12, 15, '-')                 # little perch
    # skylight glass in the big roofs
    g.hl(26, 28, 18, 'G')
    # planks bridging two gaps (burnable)
    g.hl(14, 16, 22, '-')
    g.hl(59, 61, 21, '-')
    # spawns
    for x, r in [(2, 22), (9, 22), (19, 18), (29, 18), (35, 24), (42, 24), (49, 19), (57, 19), (64, 23), (72, 23)]:
        g.mark(x, r, 'S')
    for x, r in [(11, 15), (23, 12), (39, 13), (52, 11), (68, 16), (24, 18), (45 - 4, 24)]:
        g.mark(x, r, 'w')
    for x, r, c in [(12, 22, 'b'), (18, 18, 'c'), (33 + 10, 24, 'g'), (54, 19, 'b'), (63, 23, 'c'), (3, 22, 'c')]:
        g.mark(x, r, c)
    emit('neonRooftops', 'rooftops', 'NEON ROOFTOPS', 'rooftops', 'Leap between skyscrapers. Mind the gap. Choppers drop heavy hardware.', g,
         [{'type': 'drops', 'every': [14, 22], 'xs': [8, 24, 39, 52, 68], 'pool': ['minigun', 'bazooka', 'sniper', 'rifle', 'flamer', 'bullettime']}], kill=40)

# ------------------------------------------------------------------ NIGHT TRAIN
def train():
    W, H = 96, 24
    g = G(W, H)
    roof = 12
    floor_ = 20
    cars = [(2, 21), (24, 45), (48, 69), (72, 93)]
    for x0, x1 in cars:
        g.hl(x0, x1, roof, 'M')          # roof
        g.hl(x0, x1, floor_, 'X')        # car floor
        g.vl(x0, roof, floor_, 'X')
        g.vl(x1, roof, floor_, 'X')
        g.back(x0 + 1, roof + 1, x1 - 1, floor_ - 1)
        # windows
        for wx in range(x0 + 3, x1 - 2, 5):
            g.hl(wx, wx + 1, roof + 2, 'G')
        # doors at both ends (gap in the end walls, 3 high)
        g.vl(x0, floor_ - 3, floor_ - 1, ':')
        g.vl(x1, floor_ - 3, floor_ - 1, ':')
        # interior: luggage rack + seats
        g.hl(x0 + 4, x1 - 4, roof + 4, '-')
        g.rect(x0 + 2, floor_ - 1, x0 + 3, floor_ - 1, 'W')
        g.rect(x1 - 3, floor_ - 1, x1 - 2, floor_ - 1, 'W')
        # roof hatch with ladder
        hx = (x0 + x1) // 2
        g.p(hx, roof, '-')
        g.ladder(hx, roof + 1, floor_ - 1)
        g.p(hx, roof + 1, 'H')
    # couplers between cars (walkable)
    for a, b in [(21, 24), (45, 48), (69, 72)]:
        g.hl(a + 1, b - 1, floor_, '=')
    # the locomotive end and the tail are open
    for x, r in [(4, roof), (14, roof), (27, roof), (40, roof), (52, roof), (64, roof), (76, roof), (88, roof), (9, floor_), (84, floor_)]:
        g.mark(x, r, 'S')
    for x, r in [(18, roof), (33, floor_), (57, floor_), (80, roof), (36, roof), (60, roof), (87, floor_)]:
        g.mark(x, r, 'w')
    for x, r, c in [(6, floor_, 'c'), (30, floor_, 'b'), (55, floor_, 'c'), (78, floor_, 'g'), (66, floor_, 'c')]:
        g.mark(x, r, c)
    # tunnel sweeps: a beam at standing-head height over the roof (duck!)
    roof_px = roof * 16
    tunnel = {'type': 'hazard', 'kind': 'tunnel', 'x': -2, 'y': round((roof_px - 22) / 16, 3), 'w': 2, 'h': round(7 / 16, 3),
              'on': 1.6, 'off': 13, 'phase': 3, 'warn': 2, 'damage': 25, 'knockX': 420, 'knockY': -160, 'sweep': 100}
    emit('nightTrain', 'train', 'NIGHT TRAIN', 'train', 'Brawl across a speeding train. When a tunnel comes: DUCK.', g, [tunnel], kill=24)

# ------------------------------------------------------------------ FACTORY
def factory():
    W, H = 70, 34
    g = G(W, H)
    g.rect(0, 0, W - 1, 0, 'X'); g.rect(0, H - 2, W - 1, H - 1, '#')
    g.vl(0, 0, H - 1, 'X'); g.vl(W - 1, 0, H - 1, 'X')
    g.back(1, 1, W - 2, H - 3)
    # ground floor conveyors leading into the crusher pits
    g.hl(6, 26, H - 2, '>')
    g.hl(43, 63, H - 2, '<')
    # central crusher bay
    g.rect(30, H - 9, 31, H - 3, 'X'); g.rect(38, H - 9, 39, H - 3, 'X')
    g.hl(30, 39, H - 9, 'X')
    # mezzanine catwalks
    g.hl(1, 22, 22, '=')
    g.hl(47, 68, 22, '=')
    g.hl(26, 43, 17, '=')
    g.hl(8, 24, 11, '=')
    g.hl(45, 61, 11, '=')
    g.ladder(4, 22, H - 3)
    g.ladder(65, 22, H - 3)
    g.ladder(20, 11, 21)
    g.ladder(49, 11, 21)
    g.ladder(34, 17, H - 10)
    # upper conveyors
    g.hl(12, 21, 22, '<')
    g.hl(50, 59, 22, '>')
    # machinery blocks
    g.rect(13, H - 5, 15, H - 3, 'M')
    g.rect(54, H - 5, 56, H - 3, 'M')
    g.rect(28, 13, 29, 16, 'M'); g.rect(40, 13, 41, 16, 'M')
    for x, r in [(3, H - 2), (10, H - 2), (24, H - 2), (45, H - 2), (59, H - 2), (66, H - 2), (8, 22), (61, 22), (16, 11), (53, 11)]:
        g.mark(x, r, 'S')
    for x, r in [(35, 17), (2, 22), (67, 22), (11, 11), (58, 11), (34, H - 9)]:
        g.mark(x, r, 'w')
    for x, r, c in [(18, H - 2, 'b'), (51, H - 2, 'b'), (27, 17, 'g'), (42, 17, 'c'), (23, 11, 'c'), (46, 11, 'b')]:
        g.mark(x, r, c)
    gim = [
        {'type': 'hazard', 'kind': 'crusher', 'x': 32, 'y': H - 8, 'w': 6, 'h': 6, 'on': 1.2, 'off': 4, 'warn': 1, 'damage': 999},
        {'type': 'hazard', 'kind': 'crusher', 'x': 27, 'y': H - 6, 'w': 2, 'h': 4, 'on': 0.8, 'off': 3.5, 'phase': 2, 'warn': 0.8, 'damage': 999},
        {'type': 'hazard', 'kind': 'crusher', 'x': 40, 'y': H - 6, 'w': 2, 'h': 4, 'on': 0.8, 'off': 3.5, 'phase': 0.5, 'warn': 0.8, 'damage': 999},
        {'type': 'mover', 'kind': 'hook', 'x': 10, 'y': 6, 'w': 3, 'h': 6, 'path': [[46, 0]], 'speed': 45, 'pause': 1.5},
    ]
    emit('factory', 'factory', 'FACTORY', 'factory', 'Conveyors feed the crusher. Ride the crane hook if you dare.', g, gim)

# ------------------------------------------------------------------ CONSTRUCTION SITE
def construction():
    W, H = 74, 38
    g = G(W, H)
    # ground (dirt) with a foundation pit in the middle
    g.rect(0, H - 3, W - 1, H - 1, 'D')
    g.rect(31, H - 3, 42, H - 2, '.')
    g.rect(31, H - 2, 42, H - 2, '.')
    g.hl(31, 42, H - 1, 'D')
    g.rect(30, H - 3, 30, H - 1, '#'); g.rect(43, H - 3, 43, H - 1, '#')
    # steel frame tower (left) - floors every 6 rows
    for y in [29, 23, 17, 11]:
        g.hl(4, 22, y, '=')
    for y in [29, 23, 17, 11]:            # open steel frame: pillar stubs under each floor
        g.p(4, y + 1, 'X'); g.p(22, y + 1, 'X')
    g.ladder(6, 11, H - 4)
    g.ladder(20, 17, 28)
    # scaffolding (right) - wood, burns
    for y in [30, 24, 18, 12]:
        g.hl(51, 69, y, '-')
    g.ladder(53, 12, H - 4)
    g.ladder(67, 24, 29)
    g.ladder(67, 12, 17)
    # crane mast in the middle with a deck on top
    g.vl(36, 9, H - 4, 'X')
    g.hl(30, 42, 8, '=')
    g.ladder(37, 8, H - 2)     # reaches the pit floor
    # stacks of rebar / pallets
    g.rect(25, H - 5, 27, H - 4, 'W')
    g.rect(46, H - 5, 48, H - 4, 'W')
    for x, r in [(2, H - 3), (12, 29), (15, 17), (9, 11), (27, H - 5), (47, H - 5), (60, 30), (58, 18), (65, 12), (71, H - 3)]:
        g.mark(x, r, 'S')
    for x, r in [(18, 23), (14, 11), (33, 8), (40, 8), (56, 24), (62, 12), (36, H - 1)]:
        g.mark(x, r, 'w')
    for x, r, c in [(10, 23, 'b'), (16, 29, 'c'), (64, 30, 'g'), (55, 18, 'c'), (24, H - 3, 'b'), (50, H - 3, 'c')]:
        g.mark(x, r, c)
    gim = [
        {'type': 'mover', 'kind': 'girder', 'x': 29, 'y': 2, 'w': 4, 'h': 5, 'swing': {'length': 150, 'amp': 0.55, 'period': 4.2}},
        {'type': 'mover', 'kind': 'girder', 'x': 44, 'y': 2, 'w': 4, 'h': 5, 'swing': {'length': 120, 'amp': 0.6, 'period': 3.6}},
    ]
    emit('construction', 'construction', 'CONSTRUCTION SITE', 'construction', 'Swinging girders, a bottomless foundation pit and very flammable scaffolding.', g, gim, kill=40)

# ------------------------------------------------------------------ CASINO
def casino():
    W, H = 72, 34
    g = G(W, H)
    g.hl(0, W - 1, 0, 'B'); g.rect(0, H - 2, W - 1, H - 1, '#')
    g.vl(0, 0, H - 1, 'B'); g.vl(W - 1, 0, H - 1, 'B')
    g.back(1, 1, W - 2, H - 3)
    # balconies left/right
    g.hl(1, 18, 22, '-'); g.hl(53, 70, 22, '-')
    g.hl(1, 14, 14, '-'); g.hl(57, 70, 14, '-')
    g.ladder(3, 22, H - 3); g.ladder(68, 22, H - 3)
    g.ladder(12, 14, 21); g.ladder(59, 14, 21)
    # gaming tables (metal) on the floor
    for x in [22, 32, 42]:               # card tables: stand on them, drop through them
        g.hl(x, x + 5, H - 4, '-')
    # bar counter
    g.rect(58, H - 5, 66, H - 4, 'W')
    # central upper gallery + glass windows
    g.hl(24, 47, 8, '=')
    g.hl(20, 23, 12, '-'); g.hl(48, 51, 12, '-')
    for x in range(26, 46, 4): g.p(x, 3, 'G'); g.p(x, 4, 'G')
    # elevator shaft on the left side wall area (mover handles the ride)
    for x, r in [(5, H - 2), (16, H - 2), (29, H - 2), (40, H - 2), (52, H - 2), (68 - 3, H - 5), (8, 22), (63, 22), (30, 8), (41, 8)]:
        g.mark(x, r, 'S')
    for x, r in [(6, 14), (64, 14), (35, 8), (25, H - 4), (45, H - 4), (55, 22), (15, 22)]:
        g.mark(x, r, 'w')
    for x, r, c in [(27, 12 + 4, 'l'), (36, 12 + 4, 'l'), (45, 12 + 4, 'l'), (18, H - 2, 'c'), (50, H - 2, 'b'), (60, H - 5, 'g'), (2, 14, 'c')]:
        if c == 'l':
            g.p(x, r - 4, 'l')   # chandeliers hang under the gallery
        else:
            g.mark(x, r, c)
    gim = [{'type': 'mover', 'kind': 'elevator', 'x': 19, 'y': H - 2, 'w': 2, 'h': 6, 'path': [[0, -10], [0, -24]], 'speed': 45, 'pause': 1.5}]
    emit('casino', 'casino', 'CASINO', 'casino', 'High rollers, higher chandeliers. Shoot the chains.', g, gim)

# ------------------------------------------------------------------ HARBOR DOCKS
def docks():
    W, H = 80, 32
    g = G(W, H)
    g.rect(0, H - 4, W - 1, H - 1, '~')
    # quay (left) and ship (right)
    g.rect(0, 20, 14, H - 1, '#')
    g.rect(58, 18, 79, H - 1, 'X')
    g.rect(59, 19, 78, H - 5, '.')
    g.back(59, 19, 78, H - 5)
    g.hl(59, 78, H - 5, 'X')
    g.vl(58, 21, H - 6, ':')     # door into the hold
    g.vl(58, 21, H - 6, '.')
    g.hl(62, 74, 12, '=')        # bridge
    g.ladder(64, 12, 17)
    g.ladder(76, 19, H - 6)
    g.p(76, 18, '-')
    g.rect(70, 8, 71, 11, 'M')   # funnel
    # piers
    g.hl(15, 26, 22, '-'); g.vl(18, 23, H - 1, 'W'); g.vl(24, 23, H - 1, 'W')
    g.hl(44, 57, 22, '-'); g.vl(47, 23, H - 1, 'W'); g.vl(54, 23, H - 1, 'W')
    # container stacks
    g.rect(28, 21, 33, H - 1, 'M'); g.rect(28, 17, 31, 20, 'X')
    g.rect(36, 23, 41, H - 1, 'M')
    g.rect(3, 15, 9, 19, 'M'); g.rect(5, 12, 8, 14, 'X')
    g.hl(10, 14, 14, '-')
    for x, r in [(2, 20), (11, 20), (6, 12), (20, 22), (30, 17), (38, 23), (50, 22), (61, 18), (68, 12), (72, H - 5)]:
        g.mark(x, r, 'S')
    for x, r in [(13, 14), (32, 21), (45, 22), (66, H - 5), (73, 12), (63, 18)]:
        g.mark(x, r, 'w')
    for x, r, c in [(1, 20, 'b'), (33, 21, 'c'), (40, 23, 'b'), (75, 18, 'g'), (62, H - 5, 'c'), (70, H - 5, 'b')]:
        g.mark(x, r, c)
    gim = [{'type': 'mover', 'kind': 'hook', 'x': 16, 'y': 12, 'w': 4, 'h': 8, 'path': [[38, 0]], 'speed': 40, 'pause': 2}]
    emit('docks', 'docks', 'HARBOR DOCKS', 'docks', 'Container stacks over freezing water. The crane never stops.', g, gim, kill=24)

# ------------------------------------------------------------------ OFFICE TOWER
def office():
    W, H = 70, 40
    g = G(W, H)
    tx0, tx1 = 10, 59   # tower walls (glass)
    floors = [38, 29, 20, 11]
    g.rect(tx0, 0, tx1, 1, '#')
    for y in floors:
        g.hl(tx0, tx1, y, '#')
    g.rect(tx0, 38, tx1, H - 1, '#')
    g.vl(tx0, 2, 37, 'G'); g.vl(tx1, 2, 37, 'G')
    for y0, y1 in [(2, 10), (12, 19), (21, 28), (30, 37)]:
        g.back(tx0 + 1, y0, tx1 - 1, y1)
    # stairwell ladders alternate sides; elevator shaft in the middle
    g.ladder(13, 29, 37); g.ladder(56, 20, 28); g.ladder(13, 11, 19)
    g.ladder(56, 29 + 0, 29); 
    for y in floors[1:]:
        g.p(13, y, 'H') if y == 29 or y == 11 else None
    g.p(56, 20, 'H')
    g.ladder(56, 30, 37)
    g.p(56, 29, 'H')
    # elevator shaft gap
    for y in floors[1:]:
        g.hl(33, 36, y, '.')
    # desks (wood) and cubicle walls
    for y in [37, 28, 19, 10]:
        for x in [18, 26, 42, 50]:
            g.rect(x, y, x + 2, y, 'W')
    g.vl(24, 14, 19, 'W'); g.vl(46, 23, 28, 'W')
    # server room on floor 2 (glass wall)
    g.vl(28, 21, 28, 'G')
    # roof garden on top
    g.hl(tx0 - 2, tx0 - 1, 20, '-'); g.hl(tx1 + 1, tx1 + 2, 29, '-')  # window ledges outside
    for x, r in [(16, 38), (30, 38), (40, 38), (53, 38), (16, 29), (52, 29), (22, 20), (48, 20), (18, 11), (50, 11)]:
        g.mark(x, r, 'S')
    for x, r in [(38, 29), (31, 20), (39, 11), (27, 38), (45, 20), (30, 11)]:
        g.mark(x, r, 'w')
    for x, r, c in [(20, 20, 'g'), (22 + 4, 20, 'g'), (26 - 1, 29, 'c'), (44, 38, 'b'), (54, 11, 'c'), (41, 29, 'b')]:
        g.mark(x, r, c)
    gim = [{'type': 'mover', 'kind': 'elevator', 'x': 33, 'y': 38, 'w': 4, 'h': 6, 'path': [[0, -9], [0, -18], [0, -27]], 'speed': 55, 'pause': 1.2}]
    emit('officeTower', 'office', 'OFFICE TOWER', 'office', 'Glass walls, a long way down. The server room is very flammable.', g, gim, kill=40)

# ------------------------------------------------------------------ SECRET LAB
def lab():
    W, H = 72, 34
    g = G(W, H)
    g.hl(0, W - 1, 0, 'X'); g.rect(0, H - 2, W - 1, H - 1, 'X')
    g.vl(0, 0, H - 1, 'X'); g.vl(W - 1, 0, H - 1, 'X')
    g.back(1, 1, W - 2, H - 3)
    # central low-grav chamber walls with doorways
    g.vl(24, 6, H - 6, 'X'); g.vl(47, 6, H - 6, 'X')
    g.hl(24, 47, 6, 'X')
    g.vl(24, H - 5, H - 3, ':'); g.vl(47, H - 5, H - 3, ':')
    g.vl(24, H - 5, H - 3, '.'); g.vl(47, H - 5, H - 3, '.')
    for y in [27, 22, 17, 12]:          # 5 rows apart: climbable in normal gravity too
        g.hl(29, 42, y, '=')
    # side labs: floors + ladders
    g.hl(1, 21, 22, '=');  g.hl(50, 70, 22, '=')
    g.hl(1, 14, 13, '=');  g.hl(57, 70, 13, '=')
    g.ladder(3, 22, H - 3); g.ladder(68, 22, H - 3)
    g.ladder(12, 13, 21); g.ladder(59, 13, 21)
    g.hl(17, 23, 6, '=')
    g.hl(48, 54, 6, '=')
    g.ladder(20, 6, 21); g.ladder(51, 6, 21)
    # containment tubes (glass)
    for x in [7, 9, 62, 64]:
        g.vl(x, H - 6, H - 3, 'G')
    for x, r in [(5, H - 2), (16, H - 2), (55, H - 2), (66, H - 2), (8, 22), (63, 22), (6, 13), (65, 13), (30, H - 2), (41, H - 2)]:
        g.mark(x, r, 'S')
    for x, r in [(35, 12), (35, 17), (14, 22), (57, 22), (22, 6), (49, 6)]:
        g.mark(x, r, 'w')
    for x, r, c in [(11, H - 2, 'g'), (60, H - 2, 'g'), (2, 13, 'b'), (69, 13, 'b'), (36, 22, 'c')]:
        g.mark(x, r, c)
    gim = [
        {'type': 'gravity', 'x': 25, 'y': 7, 'w': 22, 'h': H - 9, 'mult': 0.4, 'toggle': {'on': 8, 'off': 8}},
        {'type': 'hazard', 'kind': 'laser', 'x': 24, 'y': H - 5, 'w': 1, 'h': 3, 'on': 2, 'off': 3, 'warn': 0.8, 'damage': 25, 'knockX': 160},
        {'type': 'hazard', 'kind': 'laser', 'x': 47, 'y': H - 5, 'w': 1, 'h': 3, 'on': 2, 'off': 3, 'phase': 2.5, 'warn': 0.8, 'damage': 25, 'knockX': 160},
        {'type': 'hazard', 'kind': 'laser', 'x': 15, 'y': 14, 'w': 1, 'h': 8, 'on': 1.5, 'off': 4, 'phase': 1, 'warn': 0.8, 'damage': 20},
        {'type': 'hazard', 'kind': 'laser', 'x': 56, 'y': 14, 'w': 1, 'h': 8, 'on': 1.5, 'off': 4, 'phase': 3, 'warn': 0.8, 'damage': 20},
    ]
    emit('secretLab', 'lab', 'SECRET LAB', 'lab', 'Laser grids guard the doors. The test chamber flips to low gravity.', g, gim)

# ------------------------------------------------------------------ ABANDONED MINE
def mine():
    W, H = 76, 36
    g = G(W, H)
    g.rect(0, 0, W - 1, H - 1, 'D')
    # carve tunnels (back wall)
    def carve(x0, y0, x1, y1):
        g.rect(x0, y0, x1, y1, ':')
    carve(2, 26, 73, 31)      # bottom gallery (rails)
    carve(2, 17, 30, 22)      # left mid
    carve(40, 16, 73, 21)     # right mid
    carve(10, 6, 62, 11)      # top gallery
    carve(30, 17, 40, 25)     # central shaft connects mid to bottom
    carve(5, 12, 9, 16)       # left shaft
    carve(64, 12, 68, 15)     # right shaft
    carve(20, 12, 24, 16)
    carve(50, 12, 54, 15)
    # underground lake
    g.rect(33, 32, 41, 33, '~')
    g.rect(32, 31, 42, 31, ':')
    g.hl(33, 41, 32, '~')
    # floors are the dirt below each carve; add wood platforms and ladders
    g.ladder(7, 12, 31); g.ladder(66, 12, 31)
    g.ladder(22, 12, 16); g.ladder(52, 12, 15)
    g.ladder(22, 17, 22)
    g.ladder(52, 16, 21)
    g.hl(30, 40, 22, '-')
    g.ladder(35, 22, 30)
    g.hl(34, 36, 31, '-')     # little island under the shaft ladder
    g.hl(14, 26, 19, '-'); g.hl(45, 60, 18, '-')
    g.hl(28, 46, 8, '-')
    # supports (wood)
    for x in [12, 28, 47, 58]:
        g.vl(x, 27, 31, 'W')
        g.p(x, 26, ':')
    for x in [12, 28, 47, 58]:
        g.vl(x, 28, 29, ':')
    # bottom rail floor (metal)
    g.hl(2, 31, 32, 'X'); g.hl(43, 73, 32, 'X')
    g.hl(32, 32, 32, 'X'); g.hl(42, 42, 32, 'X')
    for x, r in [(4, 32), (17, 32), (25, 32), (50, 32), (62, 32), (71, 32), (15, 23), (60, 22), (18, 12), (44, 12)]:
        g.mark(x, r, 'S')
    for x, r in [(26, 23), (45, 22), (30, 12), (57, 12), (36, 22), (8, 32)]:
        g.mark(x, r, 'w')
    for x, r, c in [(10, 32, 't'), (20, 32, 't'), (55, 32, 't'), (67, 32, 't'), (24, 23, 'c'), (70, 22, 't'), (40, 12, 'b'), (14, 12, 'c')]:
        g.mark(x, r, c)
    gim = [
        {'type': 'mover', 'kind': 'cart', 'x': 2, 'y': 31.25, 'w': 2, 'h': 12, 'path': [[28, 0]], 'speed': 150, 'pause': 2.5, 'hits': {'damage': 30, 'knock': 320}},
        {'type': 'mover', 'kind': 'cart', 'x': 71, 'y': 31.25, 'w': 2, 'h': 12, 'path': [[-28, 0]], 'speed': 150, 'pause': 3.5, 'hits': {'damage': 30, 'knock': 320}},
    ]
    emit('mine', 'mine', 'ABANDONED MINE', 'mine', 'Runaway minecarts, TNT everywhere and a very cold lake.', g, gim)

# ------------------------------------------------------------------ HIDDEN LEAF FOREST (M9)
def leaf():
    W, H = 76, 36
    g = G(W, H)
    g.rect(0, 33, W - 1, H - 1, 'D')                 # forest floor
    g.vl(0, 0, 32, 'D'); g.vl(W - 1, 0, 32, 'D')     # giant trees at the edges: wall-jump surfaces
    # two giant trunks with root arches you can run under (rows 29-32 open)
    for x in (17, 57):
        g.rect(x, 4, x + 1, 28, 'D')
        g.p(x - 1, 28, 'D'); g.p(x + 2, 28, 'D')
    # left grove: branches + rope ladders, tiers 29 / 24 / 19 / 14 / 9
    g.hl(2, 10, 29, '-'); g.ladder(4, 29, 32)
    g.hl(6, 15, 24, '-'); g.ladder(9, 24, 28)
    g.hl(1, 9, 19, '-');  g.ladder(7, 19, 23)
    g.hl(8, 16, 14, '-'); g.ladder(8, 14, 18)
    g.hl(2, 10, 9, '-');  g.ladder(9, 9, 13)
    # right grove (mirror)
    g.hl(65, 73, 29, '-'); g.ladder(71, 29, 32)
    g.hl(60, 69, 24, '-'); g.ladder(66, 24, 28)
    g.hl(66, 74, 19, '-'); g.ladder(68, 19, 23)
    g.hl(59, 67, 14, '-'); g.ladder(67, 14, 18)
    g.hl(65, 73, 9, '-');  g.ladder(66, 9, 13)
    # village: two houses (thin wood walls, door gaps, orange tile roofs) and a watch tower
    for x0, x1 in ((22, 29), (46, 53)):
        g.back(x0 + 1, 27, x1 - 1, 32)
        g.vl(x0, 27, 29, 'W'); g.vl(x1, 27, 29, 'W')
        g.hl(x0 - 1, x1 + 1, 26, 'B')
    g.back(34, 18, 41, 32)
    g.vl(33, 18, 29, 'W'); g.vl(42, 18, 29, 'W')
    g.vl(33, 21, 22, '.'); g.vl(42, 21, 22, '.')       # windows
    g.hl(34, 41, 25, '-')                              # tower floor
    g.ladder(36, 25, 32)
    g.hl(32, 43, 17, 'B')                              # tower roof
    g.ladder(40, 17, 24)
    # rope bridges from the trunks to the tower roof, and branches up to the canopy
    g.hl(19, 31, 19, '-'); g.hl(44, 56, 19, '-')
    g.hl(19, 24, 12, '-'); g.ladder(22, 12, 18)
    g.hl(51, 56, 12, '-'); g.ladder(53, 12, 18)
    g.hl(30, 45, 9, '-'); g.ladder(35, 9, 16)          # canopy: the contested power-up spot
    for x, r in [(5, 33), (26, 33), (39, 33), (50, 33), (70, 33), (11, 24), (64, 24), (5, 9), (70, 9), (27, 19)]:
        g.mark(x, r, 'S')
    for x, r in [(6, 29), (69, 29), (38, 25), (12, 14), (63, 14), (29, 19), (47, 19), (21, 12), (54, 12)]:
        g.mark(x, r, 'w')
    g.mark(38, 9, 'P')
    for x, r, c in [(31, 33, 't'), (44, 33, 't'), (14, 33, 'b'), (61, 33, 'b'), (3, 19, 'c'), (72, 19, 'c'), (13, 9, 'c')]:
        g.mark(x, r, c)
    for x, y in [(25, 20), (50, 20)]:                  # hanging lanterns (fall when shot)
        g.p(x, y, 'l')
    gim = [
        {'type': 'mover', 'kind': 'platform', 'x': 38, 'y': 1, 'w': 3, 'swing': {'length': 80, 'amp': 0.6, 'period': 5}},
    ]
    emit('leafForest', 'leaf', 'HIDDEN LEAF FOREST', 'leaf', 'Giant trees to wall-jump up, a village below, a rare chakra scroll in the canopy.', g, gim, power_bias='kurama')

# ------------------------------------------------------------------ GRAND LINE SHIP (M9)
def ship():
    W, H = 78, 34
    g = G(W, H)
    g.rect(0, 30, W - 1, H - 1, '~')                 # the sea (deadly)
    g.rect(6, 20, 71, 29, 'D')                       # hull
    g.rect(0, 29, 8, 29, '~'); g.rect(69, 29, W - 1, 29, '~')
    g.p(6, 28, '.'); g.p(71, 28, '.')
    g.back(8, 21, 69, 27)                            # cargo hold
    g.rect(8, 21, 69, 27, ':')
    g.hl(4, 73, 19, 'D')                             # main deck
    g.ladder(21, 19, 27); g.ladder(56, 19, 27)       # hatches
    g.hl(12, 18, 24, '-'); g.ladder(13, 24, 27)      # cargo shelves
    g.hl(59, 65, 24, '-'); g.ladder(64, 24, 27)
    g.vl(38, 21, 25, 'W')                            # bulkhead with a door gap below
    # forecastle (bow, left) and quarterdeck (stern, right) with cabins under them
    g.hl(4, 15, 15, 'D'); g.vl(4, 16, 18, 'D'); g.back(5, 16, 14, 18)
    g.ladder(14, 15, 18)
    g.hl(60, 74, 14, 'D'); g.vl(74, 15, 18, 'D'); g.back(61, 15, 73, 18)
    g.vl(60, 15, 16, 'W'); g.ladder(62, 14, 18)
    g.hl(64, 72, 10, '-'); g.ladder(70, 10, 13)      # stern lookout
    # the mast is a rope ladder; yards (spars) are platforms, crow's nest on top
    g.hl(30, 46, 13, '-'); g.hl(33, 43, 8, '-'); g.hl(36, 40, 4, '-')
    g.ladder(38, 4, 18)
    g.ladder(31, 13, 18); g.ladder(45, 13, 18)
    for x, r in [(12, 19), (27, 19), (48, 19), (66, 19), (16, 28), (30, 28), (46, 28), (61, 28), (8, 15), (68, 14)]:
        g.mark(x, r, 'S')
    for x, r in [(34, 13), (42, 8), (16, 24), (61, 24), (24, 19), (52, 19), (10, 15), (66, 10)]:
        g.mark(x, r, 'w')
    g.mark(38, 4, 'P')
    for x, r, c in [(23, 28, 'b'), (52, 28, 'b'), (43, 28, 'g'), (26, 28, 't'), (34, 19, 'c'), (58, 19, 'c')]:
        g.mark(x, r, c)
    gim = [
        {'type': 'waves', 'every': [6, 11], 'push': 70},
        {'type': 'cannon', 'x': 7, 'y': 14, 'dir': 1, 'cooldown': 5},
        {'type': 'cannon', 'x': 72, 'y': 13, 'dir': -1, 'cooldown': 5},
        {'type': 'mover', 'kind': 'platform', 'x': 24, 'y': 9, 'w': 3, 'swing': {'length': 64, 'amp': 0.5, 'period': 4.5}},
        {'type': 'mover', 'kind': 'platform', 'x': 52, 'y': 9, 'w': 3, 'swing': {'length': 64, 'amp': 0.5, 'period': 4.5}},
    ]
    emit('grandLineShip', 'ship', 'GRAND LINE SHIP', 'ship', 'Climb the mast, fire the cannons, mind the waves. A straw hat token turns up here a lot.', g, gim, kill=40, power_bias='gear2')

# ------------------------------------------------------------------ ALIEN ENERGY PLANET (M9)
def alien():
    W, H = 76, 36
    g = G(W, H)
    g.rect(0, 32, W - 1, H - 1, 'D')                 # orange soil
    # cliffs with caves on both sides
    g.rect(0, 22, 12, 31, 'D'); g.rect(2, 27, 12, 31, ':')
    g.rect(63, 22, W - 1, 31, 'D'); g.rect(63, 27, 73, 31, ':')
    g.hl(13, 15, 22, '-'); g.ladder(14, 22, 31)
    g.hl(60, 62, 22, '-'); g.ladder(61, 22, 31)
    g.hl(1, 9, 16, '-'); g.ladder(8, 16, 21)
    g.hl(66, 74, 16, '-'); g.ladder(67, 16, 21)
    g.vl(4, 20, 21, 'G'); g.vl(71, 20, 21, 'G')     # crystals
    # floating rocks over the low-gravity fields
    g.rect(19, 26, 25, 27, 'D'); g.rect(50, 26, 56, 27, 'D')
    g.rect(28, 20, 34, 21, 'D'); g.rect(41, 20, 47, 21, 'D')
    g.rect(33, 13, 42, 14, 'D')
    g.rect(22, 8, 27, 9, 'D'); g.rect(48, 8, 53, 9, 'D')
    g.rect(37, 27, 38, 31, 'G')                      # crystal spire splitting the two fields
    for x, r in [(6, 32), (69, 32), (17, 32), (31, 32), (44, 32), (58, 32), (9, 22), (66, 22), (3, 16), (72, 16)]:
        g.mark(x, r, 'S')
    for x, r in [(22, 26), (53, 26), (31, 20), (44, 20), (24, 8), (50, 8), (34, 32)]:
        g.mark(x, r, 'w')
    g.mark(37, 13, 'P')
    for x, r, c in [(15, 32, 'g'), (60, 32, 'g'), (6, 16, 'c'), (69, 16, 'c'), (41, 32, 'b')]:
        g.mark(x, r, c)
    gim = [
        {'type': 'gravity', 'x': 16, 'y': 3, 'w': 21, 'h': 29, 'mult': 0.5},
        {'type': 'gravity', 'x': 39, 'y': 3, 'w': 21, 'h': 29, 'mult': 0.42},
        {'type': 'hazard', 'kind': 'fissure', 'x': 26, 'y': 28, 'w': 2, 'h': 4, 'on': 1.6, 'off': 4.5, 'warn': 0.9, 'damage': 22, 'knockX': 60, 'knockY': -420},
        {'type': 'hazard', 'kind': 'fissure', 'x': 48, 'y': 28, 'w': 2, 'h': 4, 'on': 1.6, 'off': 4.5, 'phase': 3, 'warn': 0.9, 'damage': 22, 'knockX': 60, 'knockY': -420},
    ]
    emit('alienPlanet', 'alien', 'ALIEN ENERGY PLANET', 'alien', 'Low-gravity fields, floating rocks and energy fissures. Home of the energy core.', g, gim, power_bias='ssj')

ALL = {'rooftops': rooftops, 'train': train, 'factory': factory, 'construction': construction, 'casino': casino,
       'docks': docks, 'office': office, 'lab': lab, 'mine': mine, 'leaf': leaf, 'ship': ship, 'alien': alien}
for name in (sys.argv[1:] or list(ALL)):
    ALL[name]()
